# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='table1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xAxis', models.CharField(default='DEFAULT VALUE', max_length=200)),
                ('yAxis', models.CharField(default='DEFAULT VALUE', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='table2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='DEFAULT VALUE', max_length=200)),
                ('prom', models.CharField(default='DEFAULT VALUE', max_length=200)),
                ('prjm', models.CharField(default='DEFAULT VALUE', max_length=200)),
                ('prod', models.CharField(default='DEFAULT VALUE', max_length=200)),
            ],
        ),
    ]
